components:
  schemas:
    Call:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://api.modelmetry.com//schemas/Call.json
          format: uri
          readOnly: true
          type: string
        CreatedAt:
          format: date-time
          type: string
        CreatedBy:
          type: string
        DurationMs:
          format: int64
          type: integer
        GuardrailID:
          type: string
        ID:
          type: string
        Metadata:
          additionalProperties: {}
          type: object
        Outcome:
          enum:
            - pass
            - fail
            - skip
            - error
          type: string
        Payload:
          $ref: "#/components/schemas/Payload"
        SummarisedEntries:
          items:
            $ref: "#/components/schemas/SummarisedEntry"
          type: array
        TenantID:
          type: string
        UpdatedAt:
          format: date-time
          type: string
        UpdatedBy:
          type: string
      required:
        - ID
        - TenantID
        - GuardrailID
        - Payload
        - Outcome
        - Metadata
        - SummarisedEntries
        - DurationMs
        - UpdatedAt
        - UpdatedBy
        - CreatedAt
        - CreatedBy
      type: object
    CallGuardrailRequestBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://api.modelmetry.com//schemas/CallGuardrailRequestBody.json
          format: uri
          readOnly: true
          type: string
        GuardrailID:
          type: string
        Payload:
          $ref: "#/components/schemas/Payload"
        TenantID:
          type: string
      required:
        - TenantID
        - GuardrailID
        - Payload
      type: object
    ChatInput:
      additionalProperties: false
      properties:
        Messages:
          items:
            $ref: "#/components/schemas/SimpleMessage"
          type: array
        Settings:
          $ref: "#/components/schemas/SimpleOptions"
      required:
        - Messages
        - Settings
      type: object
    ChatOutput:
      additionalProperties: false
      properties:
        Messages:
          items:
            $ref: "#/components/schemas/SimpleMessage"
          type: array
        Settings:
          $ref: "#/components/schemas/SimpleOptions"
      required:
        - Messages
        - Settings
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - http://api.modelmetry.com//schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type: array
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    Function:
      additionalProperties: false
      properties:
        Arguments: {}
        Name:
          type: string
      required:
        - Name
        - Arguments
      type: object
    Input:
      additionalProperties: false
      properties:
        Chat:
          $ref: "#/components/schemas/ChatInput"
        Text:
          $ref: "#/components/schemas/TextInput"
      type: object
    MetricValue:
      additionalProperties: false
      properties:
        Key:
          type: string
        Value:
          format: double
          type: number
      required:
        - Key
        - Value
      type: object
    Output:
      additionalProperties: false
      properties:
        Chat:
          $ref: "#/components/schemas/ChatOutput"
        Text:
          $ref: "#/components/schemas/TextOutput"
      type: object
    Payload:
      additionalProperties: false
      properties:
        Input:
          $ref: "#/components/schemas/Input"
        Output:
          $ref: "#/components/schemas/Output"
      type: object
    SimpleMessage:
      additionalProperties: false
      properties:
        Contents:
          items:
            $ref: "#/components/schemas/SimplePart"
          minItems: 1
          type: array
        Name:
          type: string
        Role:
          enum:
            - system
            - user
            - assistant
            - tool
            - function
          type: string
        ToolCallID:
          type:
            - string
            - "null"
        ToolCalls:
          items:
            $ref: "#/components/schemas/ToolCall"
          type: array
      required:
        - Role
        - Contents
      type: object
    SimpleOptions:
      additionalProperties: false
      properties:
        FrequencyPenalty:
          format: double
          type:
            - number
            - "null"
        Logprobs:
          type:
            - boolean
            - "null"
        MaxTokens:
          format: int64
          type:
            - integer
            - "null"
        "N":
          format: int64
          type:
            - integer
            - "null"
        PresencePenalty:
          format: double
          type:
            - number
            - "null"
        Seed:
          format: int64
          type:
            - integer
            - "null"
        Stream:
          type:
            - boolean
            - "null"
        Temperature:
          format: double
          maximum: 1
          minimum: 0
          type:
            - number
            - "null"
        Timeout:
          format: double
          minimum: 0
          type:
            - number
            - "null"
        ToolChoice:
          type:
            - string
            - "null"
        Tools:
          items:
            $ref: "#/components/schemas/Tool"
          type: array
        TopLogprobs:
          format: int64
          type:
            - integer
            - "null"
        TopP:
          format: double
          maximum: 1
          minimum: 0
          type:
            - number
            - "null"
        User:
          type:
            - string
            - "null"
      type: object
    SimplePart:
      additionalProperties: false
      properties:
        Detail:
          enum:
            - auto
            - low
            - high
          type:
            - string
            - "null"
        MimeType:
          type: string
        Text:
          type: string
        URI:
          type: string
      required:
        - Text
      type: object
    SummarisedEntry:
      additionalProperties: false
      properties:
        DurationMs:
          format: int64
          type: integer
        EvaluatorID:
          type: string
        ID:
          type: string
        InstanceID:
          type:
            - string
            - "null"
        Message:
          type: string
        Metrics:
          items:
            $ref: "#/components/schemas/MetricValue"
          type: array
        Outcome:
          type: string
        Score:
          format: double
          type:
            - number
            - "null"
        Skip:
          type: string
        TenantID:
          type: string
      required:
        - ID
        - TenantID
        - InstanceID
        - EvaluatorID
        - Outcome
        - Skip
        - Message
        - Score
        - Metrics
        - DurationMs
      type: object
    TextInput:
      additionalProperties: false
      properties:
        Text:
          type: string
      required:
        - Text
      type: object
    TextOutput:
      additionalProperties: false
      properties:
        Text:
          type: string
      required:
        - Text
      type: object
    Tool:
      additionalProperties: false
      properties:
        Description:
          type: string
        Name:
          type: string
        Parameters: {}
      required:
        - Name
        - Description
        - Parameters
      type: object
    ToolCall:
      additionalProperties: false
      properties:
        Function:
          $ref: "#/components/schemas/Function"
        ID:
          type: string
        Type:
          enum:
            - function
          type: string
      required:
        - Type
        - ID
        - Function
      type: object
  securitySchemes:
    apikeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
info:
  title: Modelmetry API
  version: 1.0.0
openapi: 3.1.0
paths:
  /calls:
    post:
      operationId: call-guardrail
      parameters:
        - explode: false
          in: query
          name: dryrun
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CallGuardrailRequestBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Call"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      security:
        - apikeyAuth: []
      summary: CallGuardrail
servers:
  - url: http://api.modelmetry.com/
